### ISSUE TITLE
Ajustar a imagem da aba "Nossa História"

### ISSUE THREAD

**Issue by thebeaoliveira** [sysadminas/sysadminas-site#4]
A imagem deverá ficar alinhada com o título "Nossa História" e não com o título "Um pouco sobre nós".

![image](https://user-images.githubusercontent.com/24916088/94999134-b4655700-058d-11eb-9fa5-a2338a1ed9dc.png)

**Comment by ronanren** [comment]
posso ser intimado sobre esta mancha?

**Comment by valescaf** [comment]
> posso ser intimado sobre esta mancha?

Oui =)

**Comment by thebeaoliveira** [comment]
Sim :)
